//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ProyectosModelo", "FK_Proyectos_Clientes", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TrabajoConLINQ3.Clientes), "Proyectos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TrabajoConLINQ3.Proyectos), true)]

#endregion

namespace TrabajoConLINQ3
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ProyectosEntities1 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ProyectosEntities1 usando la cadena de conexión encontrada en la sección 'ProyectosEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public ProyectosEntities1() : base("name=ProyectosEntities1", "ProyectosEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ProyectosEntities1.
        /// </summary>
        public ProyectosEntities1(string connectionString) : base(connectionString, "ProyectosEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ProyectosEntities1.
        /// </summary>
        public ProyectosEntities1(EntityConnection connection) : base(connection, "ProyectosEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Proyectos> Proyectos
        {
            get
            {
                if ((_Proyectos == null))
                {
                    _Proyectos = base.CreateObjectSet<Proyectos>("Proyectos");
                }
                return _Proyectos;
            }
        }
        private ObjectSet<Proyectos> _Proyectos;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Proyectos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProyectos(Proyectos proyectos)
        {
            base.AddObject("Proyectos", proyectos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProyectosModelo", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Clientes.
        /// </summary>
        /// <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="iDContacto">Valor inicial de la propiedad IDContacto.</param>
        /// <param name="calle">Valor inicial de la propiedad Calle.</param>
        /// <param name="numero">Valor inicial de la propiedad Numero.</param>
        /// <param name="piso">Valor inicial de la propiedad Piso.</param>
        /// <param name="departamento">Valor inicial de la propiedad Departamento.</param>
        /// <param name="cuidad">Valor inicial de la propiedad Cuidad.</param>
        /// <param name="provincia">Valor inicial de la propiedad Provincia.</param>
        /// <param name="pais">Valor inicial de la propiedad Pais.</param>
        /// <param name="telefono">Valor inicial de la propiedad Telefono.</param>
        /// <param name="web">Valor inicial de la propiedad Web.</param>
        public static Clientes CreateClientes(global::System.Int32 iDCliente, global::System.String nombre, global::System.Int32 iDContacto, global::System.String calle, global::System.String numero, global::System.String piso, global::System.String departamento, global::System.String cuidad, global::System.String provincia, global::System.String pais, global::System.String telefono, global::System.String web)
        {
            Clientes clientes = new Clientes();
            clientes.IDCliente = iDCliente;
            clientes.Nombre = nombre;
            clientes.IDContacto = iDContacto;
            clientes.Calle = calle;
            clientes.Numero = numero;
            clientes.Piso = piso;
            clientes.Departamento = departamento;
            clientes.Cuidad = cuidad;
            clientes.Provincia = provincia;
            clientes.Pais = pais;
            clientes.Telefono = telefono;
            clientes.Web = web;
            return clientes;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                if (_IDCliente != value)
                {
                    OnIDClienteChanging(value);
                    ReportPropertyChanging("IDCliente");
                    _IDCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCliente");
                    OnIDClienteChanged();
                }
            }
        }
        private global::System.Int32 _IDCliente;
        partial void OnIDClienteChanging(global::System.Int32 value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDContacto
        {
            get
            {
                return _IDContacto;
            }
            set
            {
                OnIDContactoChanging(value);
                ReportPropertyChanging("IDContacto");
                _IDContacto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDContacto");
                OnIDContactoChanged();
            }
        }
        private global::System.Int32 _IDContacto;
        partial void OnIDContactoChanging(global::System.Int32 value);
        partial void OnIDContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Calle
        {
            get
            {
                return _Calle;
            }
            set
            {
                OnCalleChanging(value);
                ReportPropertyChanging("Calle");
                _Calle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Calle");
                OnCalleChanged();
            }
        }
        private global::System.String _Calle;
        partial void OnCalleChanging(global::System.String value);
        partial void OnCalleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Piso
        {
            get
            {
                return _Piso;
            }
            set
            {
                OnPisoChanging(value);
                ReportPropertyChanging("Piso");
                _Piso = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Piso");
                OnPisoChanged();
            }
        }
        private global::System.String _Piso;
        partial void OnPisoChanging(global::System.String value);
        partial void OnPisoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Departamento
        {
            get
            {
                return _Departamento;
            }
            set
            {
                OnDepartamentoChanging(value);
                ReportPropertyChanging("Departamento");
                _Departamento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Departamento");
                OnDepartamentoChanged();
            }
        }
        private global::System.String _Departamento;
        partial void OnDepartamentoChanging(global::System.String value);
        partial void OnDepartamentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cuidad
        {
            get
            {
                return _Cuidad;
            }
            set
            {
                OnCuidadChanging(value);
                ReportPropertyChanging("Cuidad");
                _Cuidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cuidad");
                OnCuidadChanged();
            }
        }
        private global::System.String _Cuidad;
        partial void OnCuidadChanging(global::System.String value);
        partial void OnCuidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Provincia
        {
            get
            {
                return _Provincia;
            }
            set
            {
                OnProvinciaChanging(value);
                ReportPropertyChanging("Provincia");
                _Provincia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Provincia");
                OnProvinciaChanged();
            }
        }
        private global::System.String _Provincia;
        partial void OnProvinciaChanging(global::System.String value);
        partial void OnProvinciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pais
        {
            get
            {
                return _Pais;
            }
            set
            {
                OnPaisChanging(value);
                ReportPropertyChanging("Pais");
                _Pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pais");
                OnPaisChanged();
            }
        }
        private global::System.String _Pais;
        partial void OnPaisChanging(global::System.String value);
        partial void OnPaisChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Web
        {
            get
            {
                return _Web;
            }
            set
            {
                OnWebChanging(value);
                ReportPropertyChanging("Web");
                _Web = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Web");
                OnWebChanged();
            }
        }
        private global::System.String _Web;
        partial void OnWebChanging(global::System.String value);
        partial void OnWebChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProyectosModelo", "FK_Proyectos_Clientes", "Proyectos")]
        public EntityCollection<Proyectos> Proyectos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Proyectos>("ProyectosModelo.FK_Proyectos_Clientes", "Proyectos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Proyectos>("ProyectosModelo.FK_Proyectos_Clientes", "Proyectos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProyectosModelo", Name="Proyectos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proyectos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Proyectos.
        /// </summary>
        /// <param name="iDProyecto">Valor inicial de la propiedad IDProyecto.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
        public static Proyectos CreateProyectos(global::System.Int32 iDProyecto, global::System.String nombre, global::System.Int32 iDCliente)
        {
            Proyectos proyectos = new Proyectos();
            proyectos.IDProyecto = iDProyecto;
            proyectos.Nombre = nombre;
            proyectos.IDCliente = iDCliente;
            return proyectos;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDProyecto
        {
            get
            {
                return _IDProyecto;
            }
            set
            {
                if (_IDProyecto != value)
                {
                    OnIDProyectoChanging(value);
                    ReportPropertyChanging("IDProyecto");
                    _IDProyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDProyecto");
                    OnIDProyectoChanged();
                }
            }
        }
        private global::System.Int32 _IDProyecto;
        partial void OnIDProyectoChanging(global::System.Int32 value);
        partial void OnIDProyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                OnIDClienteChanging(value);
                ReportPropertyChanging("IDCliente");
                _IDCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCliente");
                OnIDClienteChanged();
            }
        }
        private global::System.Int32 _IDCliente;
        partial void OnIDClienteChanging(global::System.Int32 value);
        partial void OnIDClienteChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProyectosModelo", "FK_Proyectos_Clientes", "Clientes")]
        public Clientes Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ProyectosModelo.FK_Proyectos_Clientes", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ProyectosModelo.FK_Proyectos_Clientes", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ProyectosModelo.FK_Proyectos_Clientes", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes>("ProyectosModelo.FK_Proyectos_Clientes", "Clientes", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
