///////////////////////////////////////////////////////////
//  GestorPedido.cs
//  Implementation of the Class GestorPedido
//  Generated by Enterprise Architect
//  Created on:      17-Oct-2010 08:06:13 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using EjemploJPP;
namespace EjemploJPP {
	public class GestorPedido {


		private ItemMenu mItem;
		private Pedido mPedido;
		
		public GestorPedido(){

		}

		~GestorPedido(){

		}

		public virtual void Dispose(){

		}

		public void agregarItem(){
            
		}

		public void crearItem(){
            ItemMenu unItem = new ItemMenu();
            unItem.itemID = 0;
            unItem.descripcion = "Sin Descripción";
            mItem = unItem;
		}

		public void crearPedido(){

            Pedido unPedido = new Pedido();
            unPedido.estado = 0;
            unPedido.fechaDescarga = "SinFecha";
            unPedido.fechaPedido = "SinFecha";
            this.crearItem();
            mPedido = unPedido;

		}

		public void llenarPedido(){

		}

		public void mostrarPedido(){

		}

	}//end GestorPedido

}//end namespace EjemploJPP