///////////////////////////////////////////////////////////
//  Pedido.cs
//  Implementation of the Class Pedido
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2010 11:50:08 p.m.
///////////////////////////////////////////////////////////


namespace EjemploJPP {
	public class Pedido {
        		
		private int Estado;
        private string FechaDescarga;
		private string FechaPedido;
		private int PedidoID;
        private ItemMenu[] ListaItem = new ItemMenu[5];
		

        public int estado{
			//read property
			get{return Estado;}
			//write property
			set{Estado = value;}
		}
        
        public string fechaDescarga{
			//read property
			get{return FechaDescarga;}
			//write property
			set{FechaDescarga = value;}
		}
		
		public string fechaPedido{
			//read property
			get{return FechaPedido;}
			//write property
			set{FechaPedido = value;}
		}

        public void agregarItem (ItemMenu pItem)
        {
            if ListaItem[0] = pItem;
            ListaItem[longitud + 1] = item;

        }
		public Pedido(){

		}

		~Pedido(){

		}

		public virtual void Dispose(){

		}
		public void Calcular_Pedido(){

		}

		/// 
		/// <param name="item"></param>
		public void agregarItem(Abonado item){

		}

	}//end Pedido

}//end namespace EjemploJPP