///////////////////////////////////////////////////////////
//  Abonado.cs
//  Implementation of the Class Abonado
//  Generated by Enterprise Architect
//  Created on:      25-may-2012 10:10:38 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




public class Abonado {

	/// <summary>
	/// Atributos
	/// </summary>
	private int AbonadoID = 0;
	private string Nombre = "Sin Nombre";
	private string Sector = "Sin Sector";
	private string Terminal = "Sin Terminal";

	public Abonado(){

	}

	~Abonado(){

	}

	public virtual void Dispose(){

	}

	public int abonadoID{
		get;
		set;
	}

	public string nombre{
		get;
		set;
	}

	public string sector{
		get;
		set;
	}

	public string terminal{
		get;
		set;
	}

}//end Abonado