///////////////////////////////////////////////////////////
//  GestorAbonado.cs
//  Implementation of the Class GestorAbonado
//  Generated by Enterprise Architect
//  Created on:      25-may-2012 10:10:38 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

using System;


public class GestorAbonado {

	public Abonado mAbonado;

	public GestorAbonado(){

	}

	~GestorAbonado(){

	}

	public virtual void Dispose(){

	}

	public Abonado crearAbonado(){

        Abonado unAbonado = new Abonado();
        unAbonado.nombre = "Pepe";
        unAbonado.sector = "D0120";
        unAbonado.terminal = "TYO";
        return unAbonado;
	}

	public void modificarAbonado(){

	}

	public void mostrarAbonado(Abonado unAbonado){
        Console.WriteLine(unAbonado.nombre);
        Console.ReadLine();

	}

}//end GestorAbonado