///////////////////////////////////////////////////////////
//  Principal.cs
//  Implementation of the Class Principal
//  Generated by Enterprise Architect
//  Created on:      25-may-2012 10:10:38 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

using System;


public class Principal {

	public Principal(){

	}

	~Principal(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="args"></param>
	private static void Main(string[] args)
    {
        //Clase lanzadora del programa
		GestorAbonado gestAbonado = new GestorAbonado();
		Console.WriteLine("Se creo el gestor");
        gestAbonado.mostrarAbonado(gestAbonado.crearAbonado());
        Console.ReadLine();
	}

}//end Principal