///////////////////////////////////////////////////////////
//  GestorMateria.cs
//  Implementation of the Class GestorMateria
//  Generated by Enterprise Architect
//  Created on:      29-may-2012 03:55:58 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

using System.Data;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System;
using Datos;

namespace Gestores {
	public class GestorMateria {

		private Materia _materia;

		public GestorMateria(){

		}

		~GestorMateria(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="alumno"></param>
		public List<Materia> BuscarListaMaterias(Alumno alumno){

			return null;
		}

	}//end GestorMateria

}//end namespace Gestores