///////////////////////////////////////////////////////////
//  GestorAlumno.cs
//  Implementation of the Class GestorAlumno
//  Generated by Enterprise Architect
//  Created on:      29-may-2012 03:55:57 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

using System.Data;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System;
using Datos;

namespace Gestores {
	public class GestorAlumno {

		private Alumno m_Alumno = new Alumno();

		public GestorAlumno(){

            //DataClasesDataContext ctx = new DataClasesDataContext();
            m_Alumno.Legajo = "1000";
            m_Alumno.Nombre = "Alejo";
            m_Alumno.Apellido = "Valotto";
            
		}

		/// 
		/// <param name="alumno"></param>
		public Alumno BuscarAlumno(Alumno alumno){

            if ((alumno.Nombre != null) && (alumno.Nombre.Length != 0)) 
            {
               //Buscar por Nombre
            }
            if ((alumno.Apellido != null) && (alumno.Apellido.Length != 0)) 
            {
                //Buscar por Apellido
            }
            if ((alumno.Legajo != null) && (alumno.Legajo.Length != 0)) 
            {
                m_Alumno = alumno.BuscarporLegajo(alumno.Legajo);
            }
            return m_Alumno;
		}

	}//end GestorAlumno

}//end namespace Gestores