///////////////////////////////////////////////////////////
//  ItemMenu.cs
//  Implementation of the Class ItemMenu
//  Generated by Enterprise Architect
//  Created on:      17-Oct-2010 10:00:38 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////



namespace JPP2 {
    public class ItemMenu
    {

        private string Descripcion;
        private int ItemID;
        private decimal Precio;

        public ItemMenu()
        {

        }

        ~ItemMenu()
        {

        }

        public virtual void Dispose()
        {

        }

        public string descripcion
        {
            //read property
            get { return Descripcion; }
            //write property
            set { Descripcion = value; }
        }

        public int itemID
        {
            //read property
            get { return ItemID; }
            //write property
            set { ItemID = value; }
        }
        public decimal precio
        {
            //read property
            get { return Precio; }
            //write property
            set { Precio = value; }

        }//end ItemMenu
    }
}//end namespace JPP2