///////////////////////////////////////////////////////////
//  Abonado.cs
//  Implementation of the Class Abonado
//  Generated by Enterprise Architect
//  Created on:      14-oct-2010 10:10:50 p.m.
///////////////////////////////////////////////////////////
namespace JPP
{



public class Abonado {

    private int AbonadoID = 1;
    private string Nombre = "";
    private string Sector = "";
    private string Terminal = "";

	public int abonadoID{
		//read property
		get{return AbonadoID;}
		//write property
		set{AbonadoID = value;}
	}
	public string nombre{
		//read property
		get{ return Nombre;}
		//write property
		set{Nombre = value;}
	}
	public string sector{
		//read property
		get{return Sector;}
		//write property
		set{Sector = value;}
	}
	private string terminal{
		//read property
		get{return Terminal;}
		//write property
		set{Terminal = value;}
	}

    public void tratarAbonado(){
    }

    public void mostrarAbonado()
    {
    }

	public Abonado(){

	}

	~Abonado(){

	}

	public virtual void Dispose(){

	}

}//end Abonado
}