///////////////////////////////////////////////////////////
//  enumEstados.cs
//  Implementation of the Class estadosPedido
//  Generated by Enterprise Architect
//  Created on:      14-oct-2010 10:10:51 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




public enum estadosPedido : int {

	iniciado,
	encurso,
	encolado,
	entregado,
	abortado

}//end estadosPedido