///////////////////////////////////////////////////////////
//  HolaMundo.cs
//  Implementation of the Class HolaMundo
//  Generated by Enterprise Architect
//  Created on:      13-oct-2010 12:10:15 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

using System;


namespace Prueba {
	public class HolaMundo {

		public HolaMundo(){

		}

		~HolaMundo(){

		}

		public virtual void Dispose(){

		}

		public void Saludo(){
            Console.WriteLine("Hola Mundo del EA");
                Console.ReadLine();
		}

	}//end HolaMundo

}//end namespace Prueba