///////////////////////////////////////////////////////////
//  Lista de Precios.cs
//  Implementation of the Class ListaPrecios
//  Generated by Enterprise Architect
//  Created on:      14-oct-2010 10:10:51 p.m.
///////////////////////////////////////////////////////////




public class ListaPrecios {

	private int ID;
	private int Puntos_JPP;

	public ListaPrecios(){

	}

	~ListaPrecios(){

	}

	public virtual void Dispose(){

	}

	public void Actualizar(){

	}

	public void Deletear(){

	}

}//end ListaPrecios