///////////////////////////////////////////////////////////
//  Validador.cs
//  Implementation of the Class Validador
//  Generated by Enterprise Architect
//  Created on:      14-oct-2010 10:11:05 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




public class Validador {

	public Validador(){

	}

	~Validador(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="valor"></param>
	/// <param name="atributo"></param>
	/// <param name="entidad"></param>
	public bool validar(string valor, string atributo, string entidad){

		return false;
	}

}//end Validador