///////////////////////////////////////////////////////////
//  Abonado.cs
//  Implementation of the Class Abonado
//  Generated by Enterprise Architect
//  Created on:      19-Oct-2010 09:01:20 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




namespace JPP3
{
    public class Abonado
    {


        private int AbonadoID;
        private string Nombre;
        private string Sector;
        private string Terminal;

        public Abonado()
        {

        }

        ~Abonado()
        {

        }

        public virtual void Dispose()
        {

        }

        public int abonadoID
        {
            //read property
            get { return AbonadoID; }
            //write property
            set { AbonadoID = value; }
        }

        public string nombre
        {
            //read property
            get { return Nombre; }
            //write property
            set { Nombre = value; }
        }

        public string sector
        {
            //read property
            get { return Sector; }
            //write property
            set { Sector = value; }
        }
        public string terminal
        {
            //read property
            get { return Terminal; }
            //write property
            set { Terminal = value; }
        }

    }
}//end namespace JPP3