//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Curso.AplicacionFinal.WCF.Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class masterEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto masterEntities usando la cadena de conexión encontrada en la sección 'masterEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public masterEntities() : base("name=masterEntities", "masterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto masterEntities.
        /// </summary>
        public masterEntities(string connectionString) : base(connectionString, "masterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto masterEntities.
        /// </summary>
        public masterEntities(EntityConnection connection) : base(connection, "masterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alumnos> Alumnos
        {
            get
            {
                if ((_Alumnos == null))
                {
                    _Alumnos = base.CreateObjectSet<Alumnos>("Alumnos");
                }
                return _Alumnos;
            }
        }
        private ObjectSet<Alumnos> _Alumnos;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alumnos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumnos(Alumnos alumnos)
        {
            base.AddObject("Alumnos", alumnos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="masterModel", Name="Alumnos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alumnos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alumnos.
        /// </summary>
        /// <param name="nroLegajo">Valor inicial de la propiedad NroLegajo.</param>
        public static Alumnos CreateAlumnos(global::System.Int32 nroLegajo)
        {
            Alumnos alumnos = new Alumnos();
            alumnos.NroLegajo = nroLegajo;
            return alumnos;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NroLegajo
        {
            get
            {
                return _NroLegajo;
            }
            set
            {
                if (_NroLegajo != value)
                {
                    OnNroLegajoChanging(value);
                    ReportPropertyChanging("NroLegajo");
                    _NroLegajo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NroLegajo");
                    OnNroLegajoChanged();
                }
            }
        }
        private global::System.Int32 _NroLegajo;
        partial void OnNroLegajoChanging(global::System.Int32 value);
        partial void OnNroLegajoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaNac
        {
            get
            {
                return _FechaNac;
            }
            set
            {
                OnFechaNacChanging(value);
                ReportPropertyChanging("FechaNac");
                _FechaNac = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNac");
                OnFechaNacChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaNac;
        partial void OnFechaNacChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaNacChanged();

        #endregion
    
    }

    #endregion
    
}
