//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWfServiceCliente.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.develop.com/2010/math", ConfigurationName="ServiceReference1.math")]
    public interface math {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.develop.com/2010/math/math/Sumar", ReplyAction="http://schema.develop.com/2010/math/math/SumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sumar")]
        int Sumar(int xIn, int yIn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mathChannel : DemoWfServiceCliente.ServiceReference1.math, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mathClient : System.ServiceModel.ClientBase<DemoWfServiceCliente.ServiceReference1.math>, DemoWfServiceCliente.ServiceReference1.math {
        
        public mathClient() {
        }
        
        public mathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sumar(int xIn, int yIn) {
            return base.Channel.Sumar(xIn, yIn);
        }
    }
}
