///////////////////////////////////////////////////////////
//  Pedido.cs
//  Implementation of the Class Pedido
//  Generated by Enterprise Architect
//  Created on:      17-Oct-2010 10:00:38 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////


using JPP2;
namespace JPP2 {
	public class Pedido {
        private int Estado;
        private string FechaDescarga;
        private string FechaPedido;
        private int PedidoID;
        private Abonado MAbonado;
        public ItemMenu[] ListaItem = new ItemMenu[5];
        public int Longitud = 0;

		public Pedido(){

		}

		~Pedido(){

		}

		public virtual void Dispose(){

		}

		
	
		public void agregarItem(ItemMenu pItem)
        {
            if (Longitud == 0)
                 ListaItem[0] = pItem;
             else
                 ListaItem[Longitud] = pItem;
             Longitud += 1;
		}

		public void Calcular_Pedido(){

		}

        public int estado
        {
            //read property
            get { return Estado; }
            //write property
            set { Estado = value; }
        }

        public string fechaDescarga
        {
            //read property
            get { return FechaDescarga; }
            //write property
            set { FechaDescarga = value; }
        }

        public string fechaPedido
        {
            //read property
            get { return FechaPedido; }
            //write property
            set { FechaPedido = value; }
        }

        public int pedidoID
        {
            //read property
            get { return PedidoID; }
            //write property
            set { PedidoID = value; }
        }

        public Abonado mAbonado
        {
            get { return MAbonado; }
            set { MAbonado = value; }
        }
	}//end Pedido

}//end namespace JPP2