///////////////////////////////////////////////////////////
//  Abonado.cs
//  Implementation of the Class Abonado
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2010 07:22:40 p.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




namespace EjemploJPP {
    public class Abonado
    {

        /// <summary>
        /// Atributos
        /// </summary>
        private int AbonadoID = 0;
        private string Nombre = "Sin Nombre";
        private string Sector = "Sin Sector";
        private string Terminal = "Sin Terminal";


        public int abonadoID
        {
            //read property
            get { return AbonadoID; }
            //write property
            set { AbonadoID = value; }
        }

        public string nombre
        {
            //read property
            get { return Nombre; }
            //write property
            set { Nombre = value; }
        }

        public string sector
        {
            //read property
            get { return Sector; }
            //write property
            set { Sector = value; }
        }
        public string terminal
        {
            //read property
            get { return Terminal; }
            //write property
            set { Terminal = value; }
        }

        public Abonado()
        {

        }

        ~Abonado()
        {

        }

        public virtual void Dispose()
        {

        }

        public void suscripcion()
        {

        }
    }
}//end namespace EjemploJPP