///////////////////////////////////////////////////////////
//  GestorIU.cs
//  Implementation of the Class GestorIU
//  Generated by Enterprise Architect
//  Created on:      19-Oct-2010 09:01:20 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

using System;
using JPP3;
namespace JPP3
{
    public class GestorIU
    {
        public GestorAbonado unG_Abonado = new GestorAbonado();
        public GestorPedido unG_Pedido = new GestorPedido();
        public GestorIU()
        {

        }

        ~GestorIU()
        {

        }

        public virtual void Dispose()
        {

        }

        public void ingresarAbonado()
        {

            unG_Abonado.crearAbonado();
            unG_Abonado.llenarAbonado();
            unG_Abonado.mostrarAbonado();

        }

        public void ingresarPedido()
        {
            unG_Pedido.crearPedido();
            if (unG_Abonado != null)
                unG_Pedido.llenarPedido(unG_Abonado.mAbonado);
            unG_Pedido.mostrarPedido();
        }

        public void SeleccionarEntidad()
        {
            int opcion;


            //Muestra Menu Inicial
            Console.Clear();
            Console.WriteLine("Ejemplo de Aplicacion");
            Console.WriteLine("---------------------");

            Console.WriteLine("Seleccionar");
            Console.WriteLine("Tratar Abonado: 1");
            Console.WriteLine("Tratar Pedido: 2");
            Console.WriteLine("Salir: 0");

            Console.Write("Opcion  >");
            opcion = Convert.ToInt32(Console.ReadLine());

            while (opcion != 0)
            {

                if (opcion == 1)
                {
                    Console.Clear();
                    Console.WriteLine("Tratar Abonado");
                    this.ingresarAbonado();
                    Console.ReadLine();
                }
                else
                {
                    Console.Clear();
                    Console.WriteLine("Tratar Pedido");
                    this.ingresarPedido();
                    Console.ReadLine();
                }
                Console.Clear();
                Console.WriteLine("Ejemplo de Aplicacion");
                Console.WriteLine("---------------------");

                Console.WriteLine("Seleccionar");
                Console.WriteLine("Tratar Abonado: 1");
                Console.WriteLine("Tratar Pedido: 2");
                Console.WriteLine("Salir: 0");

                Console.Write("Opcion >");
                opcion = Convert.ToInt32(Console.ReadLine());

            }
            Console.Clear();
            Console.WriteLine("Fin del Programa");
            Console.WriteLine("Una tecla para terminar");
            Console.Read();

        }//end GestorIU

    }
}//end namespace JPP3