///////////////////////////////////////////////////////////
//  Principal.cs
//  Implementation of the Class Principal
//  Generated by Enterprise Architect
//  Created on:      19-Oct-2010 09:01:21 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




namespace JPP3 {
	public class Principal {

		public Principal(){

		}

		~Principal(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="args"></param>
		private static void Main(string[] args){
            GestorIU miIU = new GestorIU();
            miIU.SeleccionarEntidad();
		}

	}//end Principal

}//end namespace JPP3