///////////////////////////////////////////////////////////
//  GestorAbonado.cs
//  Implementation of the Class GestorAbonado
//  Generated by Enterprise Architect
//  Created on:      15-oct-2010 08:30:37 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

namespace JPP
{

public class GestorAbonado {

	public GestorAbonado(){

	}

	~GestorAbonado(){

	}

	public virtual void Dispose(){

	}

	public void actualizarAbonado(){

	}

	public void crearAbonado(){

	}

	public void mostrarAbonado(){

	}

    public void tratarAbonado()
    {
    }
}//end GestorAbonado
}