///////////////////////////////////////////////////////////
//  gestorEntidades.cs
//  Implementation of the Class gestorEntidades
//  Generated by Enterprise Architect
//  Created on:      15-oct-2010 09:20:42 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////

using System;
using EjemploATS;
using JPP;


public class gestorEntidades {
	
	private string a = "0";
    private int b = 1;

	public gestorEntidades(){

	}

	~gestorEntidades(){

	}

	public virtual void Dispose(){

	}
    public string mostrarOpciones()
    {
        string k;
        Console.WriteLine("Opcion 1 - Abonado");
        Console.WriteLine("Opcion 2 - Pedido");
        Console.Write("Opcion:");
        k = Console.ReadLine();
        return k;
    }

	/* Begin - EA generated code for  Activities and Interactions */

	public void seleccionarEntidad ()
	{
		// behavior is a Activity
        string opcion;
		opcion = mostrarOpciones();
		if (String.Compare(opcion,"2") == 0)
		{
			//Tratar Pedido;
            Console.Clear();
            Console.WriteLine ("Tratar Pedido");
		}
        else if (String.Compare(opcion,"1") == 0)
		{
			
            GestorAbonado gAbonado = new GestorAbonado();
			gAbonado.tratarAbonado();
			gAbonado.mostrarAbonado();
            Console.WriteLine("Tratar Abonado");
		}
	}


	/* End - EA generated code for  Activities and Interactions */

}//end gestorEntidades