///////////////////////////////////////////////////////////
//  Item_Menu.cs
//  Implementation of the Class ItemMenu
//  Generated by Enterprise Architect
//  Created on:      14-oct-2010 10:10:51 p.m.
///////////////////////////////////////////////////////////




public class ItemMenu {

	string Descripcion ="";
	int ItemID = 0;
	
	public string descripcion{
		//read property
		get{return Descripcion;}
		//write property
		set{Descripcion = value;}
	}
	public int itemID{
		//read property
		get{return ItemID;}
		//write property
		set{ItemID = value;}
	}
	public ListaPrecios m_ListaPrecios;

	public ItemMenu(){

	}

	~ItemMenu(){

	}

	public virtual void Dispose(){

	}

}//end ItemMenu